### PR TITLE
removed object.assign

### PR DESCRIPTION
**Pull request by jerairrest**
removed object.assign to make it so a polyfill is not necassary

### CODE REVIEW

**Comment by lcpunch** [comment]
Nice, 
it would be good to fix this example also
https://github.com/gor181/react-chartjs-2/blob/master/example/src/components/randomizedLine.js#L50

**Comment by jerairrest** [comment]
Nice catch!

**Comment by jerairrest** [comment]
@gor181 can you please merge and publish?

**Comment by iamakulov** [comment]
Hi! Can this be published please? The latest version on npm is currently 2.0.0.

**Comment by jerairrest** [comment]
@gor181

**Comment by fdeurioste** [comment]
+1

**Comment by gor181** [comment]
Hello, apologies for delay and thanks for patience.
Published as `2.0.5`

**Comment by iamakulov** [comment]
Thanks, @gor181!

**Comment by gor181** [comment]
All the praise to @jerairrest 👍

**Pull request merged**
