### PR TITLE
Export Chart.

### LINKED ISSUE #62: Export Chart constructor
Is there any reason why not to export Chart constructor? For example I need to monkey-patch things like this https://jsfiddle.net/56s9av1j/.

I can PR this.

### PR DESCRIPTION
**Pull request by octalmage**
Resolves #62. 

Can be used like this: 

```
import { Chart } from 'react-chartjs-2';

Chart.pluginService.register({
    afterDraw: function (chart, easingDecimal) {
        // Plugin stuff.
    }
});
```

I wasn't sure if I should include all of the built changes, or if you build them on release, but here you go!

### CODE REVIEW

**Comment by gor181** [comment]
heya @octalmage ,

Thanks a lot for this.
Can you just please add it to the readme? If you do not have time do let me know, I'll add it after we merge the PR.

**Comment by octalmage** [comment]
Of course! I'll make the change soon.

**Comment by octalmage** [comment]
@gor181 changes pushed! 

What do you think? 

https://github.com/octalmage/react-chartjs-2/tree/export-chart#chartjs-object

**Comment by gor181** [comment]
it's awesome @octalmage 

merged in!

**Pull request merged**
