### PR TITLE
make chart.js pearDependency

### PR DESCRIPTION
**Pull request by adammockor**
It's more flexible approach and since this is only wrapper, it make sense.

### CODE REVIEW

**Comment by gor181** [comment]
hey @adammockor ,

This can be merged, just pleased add chart.js to devDependencies too.
Otherwise tests are failing.

cheers,

**Comment by adammockor** [comment]
Test are still failing, I will look into that.

**Comment by gor181** [comment]
Hey,

Thats because chart.js has a bug in 2.4.0 for getDatasetAtEvent.

devDependencies are good now.

Will look on how to overcome that bug in tests so we can run most recent chart.js versions

**Comment by gor181** [comment]
Thanks for the contribution. Will merge it later today :)

**Comment by adammockor** [comment]
Ok. Thank you.

This is [possible solution](https://github.com/chartjs/Chart.js/pull/3608#issuecomment-264236077) if you want to patch it internally or just for the test. If you do, tests will pass.

I can add it to this pull request, but it depends on your decision.

**Comment by jerairrest** [comment]
@adammockor for now if you want to add that patch in to make the tests pass I'd be cool with that. Also, would you consider this a breaking change for people who are not currently using chartjs as their own dependency?

**Comment by adammockor** [comment]
It is probably a breaking change. If somebody has "^1.6.0" in package.json without own chartjs dependency, it can break CI build or something.

**Comment by jerairrest** [comment]
@gor181 What do you think? Would this make it 2.0.0  or do we go to 1.7.0? 

Either way the README.md would need to be updated?

**Comment by gor181** [comment]
Yeh well... this is a major so we should go for `2.0`

Maybe just to add in README as you said, something as "Since version 2.0 chart.js is a peerDependency, make sure you have one defined in your project"

Thanks both!

**Comment by jerairrest** [comment]
I'm going to merge into a new branch for now. I believe this change will fix a few other issues with tooltips not working. Currently 1.6.2 pulls chart.js 2.3.0 while 1.5.1 pulls chartjs. 2.4.0.

**Pull request merged**
