### PR TITLE
add react-storybook

### PR DESCRIPTION
**Pull request by zeroasterisk**
Checkout the new package and setup instructions on the README...

See if you like the idea...  
React Storybook is awesome, and it can auto-publish to github pages for you....

### CODE REVIEW

**Comment by gor181** [comment]
Heya @zeroasterisk ,

WOW! This would be awesome. I have tried to boot it up by running `npm run storybook`:

image

Building doesn't help prior running:

image

It seems to work fine if I just run examples with `npm start` and open `localhost:8000`.

It could be that the issue is related as I'm using `export` instead of `module.exports` or similar.

Thoughts?

Thanks,

**Comment by zeroasterisk** [comment]
Your `npm start` does some hijackery on the package.json --> aliasify --> it makes *this* into the package.  (via that starter package you use)

The way I got around it, is documented in your readme... via [npm link](https://docs.npmjs.com/cli/link)

```
cd <repo-root>
npm build
npm link
npm link react-chartjs-2
```

Though... I think a better solution might be to directly include via a relative path vs. the `react-chartjs-2` package name... makes the examples a little less "real world" but makes dev simpler.

**Comment by gor181** [comment]
Ah! Yeh, agreed. Would be awesome to require the examples in a relative manner. I can do it in another branch for `examples` folder, can you make story book to use relative paths?

I appreciate your help, storybook is niceee

**Comment by jerairrest** [comment]
Can master get merged into this? :) thanks!

**Comment by jerairrest** [comment]
Well I guess we'll consider this not mergeable :(

**Comment by zeroasterisk** [comment]
Ha. Sorry I never saw the previous message. Let me dust this off and see if I can easily revive it.

**Comment by jerairrest** [comment]
Awesome man! Looking forward to the PR.

**Comment by zeroasterisk** [comment]
easy peasey #121

**Pull request closed without merging**
