### PR TITLE
Solve #48 - Bug in deepEquals

### PR DESCRIPTION
**Pull request by micouz**
Solves #48

### CODE REVIEW

**Comment by gor181** [comment]
Hey @micouz ,

Thanks a lot for submitting the PR.
Would it be possible for you to add some tests for `deepEquals`, so far we have none and it would prevent the issues you found in the first place.

Thanks in advance,

**Comment by micouz** [comment]
Hi @gor181 ,

My PR is a quick fix to solve a problem I have in a production app. I agree it's not optimal, however I don't intend to spend time to write tests for this particular problem. It has already been solved quite a few times (underscore, lodash, ramda and node-deep-equal are the implementations I know of), so I'd rather use one of those proved implementations instead.

The good thing about Lodash is that its functions are available as individual components on npm, so there is no need to import the whole library. Here's the one we need:
https://www.npmjs.com/package/lodash.isequal

What do you think ?

**Comment by gor181** [comment]
Hey @micouz ,

I agree.
Are you using your fork at the moment?

**Comment by micouz** [comment]
@gor181 Right now as a very short term solution I just applied the quick fix directly in the lib files in node_modules. Not pretty, but it's a small early stage project and I'm the whole team, so it can wait a while as is until a definitive solution is reached.

**Comment by gor181** [comment]
hey @micouz ,

Do you have an example where the deepEqual fails? I have tried to reproduce and I have noticed that sometimes there is "magical" `_meta` property (check image below):

image

Is this the same behaviour you have been experiencing?

**Comment by gor181** [comment]
What's even worse I think that chart.js directly mutates the props:
https://github.com/chartjs/Chart.js/blob/master/src/core/core.controller.js#L612-L633

by adding the `_meta` tag.

**Comment by micouz** [comment]
Hi @gor181,

I confirm you that chart.js does mutate its props. I discovered that because I sometimes deep-freeze my app state to prevent accidental mutations.

Tomorrow I'll try to give you more info so you can reproduce the bug.

Cheers,

**Comment by micouz** [comment]
Hi @gor181,
I can't reproduce the bug anymore, which is both good and bad. It would still be a good idea to switch to lodash.isequal, but from my side there's not point in merging this PR anymore.

**Comment by gor181** [comment]
hey @micouz ,

Thanks, I have started to work on implementation which includes isEqual.
Should be done soon.

Thanks for all the efforts.

**Comment by micouz** [comment]
Thanks @gor181, I'll close this up then.
Cheers,

**Pull request closed without merging**
