### PR TITLE
update chart dynamically

### PR DESCRIPTION
**Pull request by jerairrest**
Fixing issue https://github.com/gor181/react-chartjs-2/issues/35 as per  @mekwall proposed change.

### CODE REVIEW

**Comment by gor181** [comment]
Hey @jerairrest ,

Seems that there are some conflicts around.
I think rebasing the master and building again would do it.

While you are there please change `var` to `const`

Cheers,

**Comment by jerairrest** [comment]
yep. I see it. fixing now :)

**Comment by jerairrest** [comment]
after ci this should be good to go.

**Comment by gor181** [comment]
Great cheers! 👍

**Pull request merged**
