### PR TITLE
Rendering improvements

### PR DESCRIPTION
**Pull request by gor181**
add lodash.isEqual dependency and remove legacy code
add mocha/enzyme/chai/sinon and remove jest
add spec and remove old spec

### CODE REVIEW

**Comment by jerairrest** [comment]
can you pull latest master into this? Is it just the fact TravisCI is failing that this is still pending?

**Comment by gor181** [comment]
hey @jerairrest ,

Yeh i'll rebase master asap, tests are failing due to some sort of misconfiguration on CI.
However those are working quite nice locally...

Need to figure out why the heck it's not working as it's supposed to.
I hope to get onto this over weekend.

Cheers,

**Comment by gor181** [comment]
Hey @jerairrest ,

If you have time these days I would appreciate if you could try this branch out a bit.
I have rebased master.

Cheers,
Goran

**Comment by jerairrest** [comment]
Will do!

**Comment by jerairrest** [comment]
Everything is looking good to me. I'm going to do a little bit more testing but for now 👍

**Comment by gor181** [comment]
I'm going to merge this in @jerairrest

**Comment by jerairrest** [comment]
👍

**Pull request merged**
