### PR TITLE
No unnecessary re-rendering with onElementsClick

### LINKED ISSUE #16: Chart component is updated every time onElementsClick is installed
Hello,

Thanks a lot for this library, is is really useful!

I'm having a small problem with chart being updated every time parent's state changes.
It seems like `ChartComponent#shouldComponentUpdate()` method always returns `true` when props contain `onElementsClick` function.
This is probably caused by `deepEqual` expecting only arguments of type 'object':
`typeof objA !== 'object' || objA === null || typeof objB !== 'object' || objB === null`
and `typeof props.onElementsClick === 'function'`.

I'd be happy to provide a PR but want to discuss the solution:
 1. just add `onElementsClick` to the list of excluded properties in  `shouldComponentUpdate()`;
 2. make `shouldComponentUpdate()` compare only `props.data`, `props.legend`, `props.options`, `props.type` and remove code for exclusion entirely.

Please let me know what is best and if I can submit a PR.

### PR DESCRIPTION
**Pull request by lutovich**
Fixes #16

### CODE REVIEW

**Comment by gor181** [comment]
thanks @lutovich , really appreciated

**Comment by lutovich** [comment]
@gor181 thanks!

I've also tried to add some simple unit tests with Jest but it did not work.
There appeared some dependency issue with npm:

```
$ npm install --save-dev jest babel-jest babel-polyfill
npm WARN package.json react-chartjs-2@1.2.3 No license field.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "jest" "babel-jest" "babel-polyfill"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@0.14.8 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-test-renderer@15.3.0 wants react@^15.3.0
```

Not sure how to solve it, I'm really new to all this Javascript stuff.
I can submit tests as a separate PR if you know how to fix this dependency problem.

**Comment by gor181** [comment]
Hey @lutovich ,

I have been using mocha so far, but would be more than happy to checkout Jest.
If you have code by hand please be kind to submit a PR and I'll take a look.

Cheers!

**Comment by gor181** [comment]
btw, try node 5 and npm 3.

if you use `nvm` it's easy as `nvm install 5`

**Pull request merged**
